# Block admin routing
monsieurbiz_sylius_cms_block_admin:
    resource: |
        alias: monsieurbiz_cms_block.block
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: monsieurbiz_cms_block
    type: sylius.resource
