sylius_grid:
    grids:
        monsieurbiz_cms_block:
            driver:
                name: doctrine/orm
                options:
                    class: '%monsieurbiz_cms_block.model.block.class%'
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            limits: [25, 50, 100, 200]
            fields:
                code:
                    type: string
                    label: monsieurbiz_cms_block.ui.form.code
                    sortable: ~
                name:
                    type: string
                    label: monsieurbiz_cms_block.ui.form.name
                    sortable: translation.name
                enabled:
                    type: twig
                    label: monsieurbiz_cms_block.ui.form.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                        label: monsieurbiz_cms_block.ui.actions.create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
            filters:
                code:
                    type: string
                    label: monsieurbiz_cms_block.ui.form.code
                name:
                    type: string
                    label: monsieurbiz_cms_block.ui.form.name
                    options:
                        fields: [translation.name]
                enabled:
                    type: boolean
                    label: monsieurbiz_cms_block.ui.form.enabled
                content:
                    type: string
                    label: monsieurbiz_cms_block.ui.form.content
                    options:
                        fields: [translation.content]
