services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusCmsBlockPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusCmsBlockPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    # Block Forms
    MonsieurBiz\SyliusCmsBlockPlugin\Form\Type\BlockType:
        arguments:
            $dataClass: '%monsieurbiz_cms_block.model.block.class%'
            $validationGroups: ['monsieurbiz']
    MonsieurBiz\SyliusCmsBlockPlugin\Form\Type\BlockTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_cms_block.model.block_translation.class%'
            $validationGroups: ['monsieurbiz']
