MonsieurBiz\SyliusCmsBlockPlugin\Entity\BlockTranslation:
    properties:
        name:
            -   NotBlank:
                    groups: [monsieurbiz]
            -   Length:
                    min: 2
                    max: 255
                    groups: [monsieurbiz]
        content:
            -   NotBlank:
                    groups: [monsieurbiz]
