monsieurbiz_sylius_richeditor:
    ui_elements:
        monsieurbiz_cms_block.block:
            alias: block
            title: 'monsieurbiz_cms_block.ui_element.block.title'
            description: 'monsieurbiz_cms_block.ui_element.block.description'
            icon: majesticons:code-block-line
            wireframe: block
            tags: [ default, block ]
            classes:
                form: MonsieurBiz\SyliusCmsBlockPlugin\Form\Type\UiElement\BlockType
                ui_element: MonsieurBiz\SyliusCmsBlockPlugin\UiElement\BlockUiElement
            templates:
                admin_render: '@MonsieurBizSyliusCmsBlockPlugin/admin/uielement/block.html.twig'
                front_render: '@MonsieurBizSyliusCmsBlockPlugin/shop/uielement/block.html.twig'
